### PR TITLE
1.4.0

### PR DESCRIPTION
**Pull request by Novido**
- Changed the layout of the HUD boxes.

- Added BB stats

- Added a settings page for future customization

- Added customizable file path
!!! This has unfortunately broken the automatic recognition of client. This needs to be checked. !!!

### CODE REVIEW

**Comment by eduherminio** [comment]
It's nice to see someone else interested in contributing to this.

I'm also preparing some changes to be merged, and I noticed you've made some of them too.
I've isolated my changes that only related to code refactorings (adding/fixing comments, simplifications, etc.) in PR #2 and I'm planning to add some others after that one with specific features, such as adding settings as you did, and some others.

Could I suggest you to separate your changes in different pull requests? That may make it easier for @ylboerner to review them.

**Comment by Novido** [comment]
@eduherminio I only have to figure out how to revert my commits and split them into new smaller ones. Unless you have any tips on how to do it?

**Comment by Novido** [comment]
I'll divide this into smaller pull requests.

**Comment by eduherminio** [comment]
A simple approach is (for each commit):
* Create a new branch from `dev`.
* `git cherrypick <your_commit_id>`.
* `git reset --mixed <old_commit_id>`, being `<old_commit_id>` the id of the last commit in `dev` branch.
Doing that you'll get your changes of `<your_commit_id>` back, ready to be split into different commits / along different branches.

**Pull request closed without merging**
